//------------------------------------------------------------------------------
// file:    Internal_Graphics.h
// author:    Hazel Benting
// brief:    Manipulate and draw basic vector shapes
//
// Copyright � 2026DigiPen, All rights reserved.
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Include Files:
//------------------------------------------------------------------------------

#include<Metal/Metal.h>
#include<Metal/MTLHeap.h>
#include<Metal/MTLEvent.h>
#include<Metal/MTLFence.h>
#include<Metal/MTLTypes.h>
#include<Metal/MTLBuffer.h>
#include<Metal/MTLDevice.h>
#include<Metal/MTLTensor.h>
#include<Metal/MTLDefines.h>
#include<Metal/MTLLibrary.h>
#include<Metal/MTLSampler.h>
#include<Metal/MTLTexture.h>
#include<Metal/MTLArgument.h>
#include<Metal/MTLCounters.h>
#include<Metal/MTLDrawable.h>
#include<Metal/MTLPipeline.h>
#include<Metal/MTLResource.h>
#include<Metal/MTLAllocation.h>
#include<Metal/MTLGPUAddress.h>
#include<Metal/MTLIOCompressor.h>
#include<Metal/MTL4Archive.h>
#include<Metal/MTLBlitPass.h>
#include<Metal/MTLDataType.h>
#include<Metal/MTLLogState.h>
#include<Metal/MTL4Compiler.h>
#include<Metal/MTL4Counters.h>
#include<Metal/MTLRenderPass.h>
#include<Metal/MTLComputePass.h>
#include<Metal/MTLFunctionLog.h>
#include<Metal/MTLPixelFormat.h>
#include<Metal/MTLCaptureScope.h>
#include<Metal/MTLCommandQueue.h>
#include<Metal/MTLDepthStencil.h>
#include<Metal/MTLResidencySet.h>
#include<Metal/MTLBinaryArchive.h>
#include<Metal/MTLCommandBuffer.h>
#include<Metal/MTLCaptureManager.h>
#include<Metal/MTLCommandEncoder.h>
#include<Metal/MTLDynamicLibrary.h>
#include<Metal/MTLFunctionHandle.h>
#include<Metal/MTLIOCommandQueue.h>
#include<Metal/MTLRenderPipeline.h>
#include<Metal/MTLArgumentEncoder.h>
#include<Metal/MTLComputePipeline.h>
#include<Metal/MTLIOCommandBuffer.h>
#include<Metal/MTLLinkedFunctions.h>
#include<Metal/MTLVertexDescriptor.h>
#include<Metal/MTLFunctionStitching.h>
#include<Metal/MTLRasterizationRate.h>
#include<Metal/MTLFunctionDescriptor.h>
#include<Metal/MTLDeviceCertification.h>
#include<Metal/MTLAccelerationStructure.h>
#include<Metal/MTL4RenderPass.h>
#include<Metal/MTL4BufferRange.h>
#include<Metal/MTL4CommandQueue.h>
#include<Metal/MTL4CompilerTask.h>
#include<Metal/MTL4ArgumentTable.h>
#include<Metal/MTL4CommandBuffer.h>
#include<Metal/MTL4PipelineState.h>
#include<Metal/MTL4BinaryFunction.h>
#include<Metal/MTL4CommandEncoder.h>
#include<Metal/MTL4CommitFeedback.h>
#include<Metal/MTL4RenderPipeline.h>
#include<Metal/MTL4ComputePipeline.h>
#include<Metal/MTL4CommandAllocator.h>
#include<Metal/MTL4LibraryDescriptor.h>
#include<Metal/MTL4LinkingDescriptor.h>
#include<Metal/MTL4FunctionDescriptor.h>
#include<Metal/MTL4AccelerationStructure.h>
#include<Metal/MTL4MeshRenderPipeline.h>
#include<Metal/MTL4TileRenderPipeline.h>
#include<Metal/MTL4RenderCommandEncoder.h>
#include<Metal/MTL4ComputeCommandEncoder.h>
#include<Metal/MTL4MachineLearningPipeline.h>
#include<Metal/MTL4BinaryFunctionDescriptor.h>
#include<Metal/MTL4LibraryFunctionDescriptor.h>
#include<Metal/MTL4StitchedFunctionDescriptor.h>
#include<Metal/MTL4SpecializedFunctionDescriptor.h>
#include<Metal/MTL4PipelineDataSetSerializer.h>
#include<Metal/MTL4MachineLearningCommandEncoder.h>

